### PR TITLE
Update confidence intervals.md

### PR DESCRIPTION
**Pull request by Expertium**
Now all you have to do it just change `method` to `'BCA'` in evaluate.py. Btw, is there a way to make a pull request with more than one edited file? I mean, I don't know how to make a pull request with changes to both readme and evaluate.py.

### CODE REVIEW

**Comment by Expertium** [comment]
Oh, and add `n_resamples=300_000,` to scipy.stats.bootstrap(). It's 9999 by default, but since this isn't very computationally expensive for a small dataset, I decided to increase it.

**Review by Expertium — COMMENTED** [review]
```
    CI_99_bootstrap = scipy.stats.bootstrap(
        (identifiers,),
        statistic=weighted_mean,
        confidence_level=0.99,
        axis=0,
        method="BCa",
        n_resamples=300_000,
    )
```

**Comment by Expertium** [comment]
A little bit more about significant digits. In physics and engineering it's easy - a measurement device (ruler, thermometer, etc.) has a known measurement error. For example, a ruler might have a measurement error of ±0.1 cm. In that case, reporting "12.4 cm" makes sense, but reporting "12.42 cm" does not.
But in machine learning it's more complicated. As a general rule of thumb, *the last sig-dig in the mean value is at the same decimal decade as the first sig-dig (the first non-zero) in the confidence interval*.
Btw, I will further edit both this and the main repo, as I just realized that I did not adhere to that rule.

**Comment by Expertium** [comment]
You can merge this now.

**Comment by L-M-Sherlock** [comment]
> I mean, I don't know how to make a pull request with changes to both readme and evaluate.py.

You can edit it in your own branch: https://github.com/Expertium/fsrs-vs-sm17/tree/patch-4

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
